Table Definations 
Table 1 : user

CREATE TABLE `user` (
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Table 2 : user_roles

CREATE TABLE `user_roles` (
  `USER_ROLE_ID` INT(10) UNSIGNED NOT NULL,
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `AUTHORITY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  KEY `FK_user_roles` (`USER_ID`),
  CONSTRAINT `FK_user_roles` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Table 3 : user_location

CREATE TABLE `user_location` (
  `USER_LOCATION_ID` INT(10) UNSIGNED NOT NULL,
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `LOCATION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_LOCATION_ID`),
  KEY `FK_user_location` (`USER_ID`),
  CONSTRAINT `FK_user_location` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL,
  `AUTHORITY` VARCHAR(45) NOT NULL,
  `LOCATION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO user (USER_ID, USERNAME, PASSWORD, ENABLED, AUTHORITY, LOCATION) VALUES (100, 'prathamesh', '123456', TRUE, 'ROLE_USER', 'prathm');

INSERT INTO user (USER_ID, USERNAME, PASSWORD, ENABLED, AUTHORITY, LOCATION) VALUES (101, 'admin', 'admin', TRUE, 'ROLE_ADMIN', 'admin');


Data Definations :

INSERT INTO user (USER_ID, USERNAME,PASSWORD, ENABLED) VALUES (100, 'prathamesh', '123456', TRUE);

INSERT INTO user_roles (USER_ROLE_ID, USER_ID,AUTHORITY) VALUES (1, 100, 'ROLE_USER');

INSERT INTO user_location (USER_LOCATION_ID, USER_ID, LOCATION) VALUES (1, 100, 'fprath');


